spring.application.name=core
spring.profiles.active=dev
server.port=9511
spring.config.import=optional:configserver:http://localhost:9510
spring.cloud.config.username=<YOUR_CONFIG_SERVER_USERNAME>
spring.cloud.config.password=<YOUR_CONFIG_SERVER_PASSWORD>
#Debugging
logging.level.org.springframework.security=DEBUG