# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://<YOUR_DEV_DB_HOST>:<PORT>/<YOUR_DEV_DB_NAME>?sslmode=require&currentSchema=aws_woc_dev
spring.datasource.username=<YOUR_DEV_DB_USERNAME>
spring.datasource.password=<YOUR_DEV_DB_PASSWORD>

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

jwt.secret=<YOUR_DEV_JWT_SECRET_KEY>
jwt.expiration=900000


swagger.server.url=https://amazon-woc-api.monkhubtech.com

aws.s3.bucket-name=dss-we-storage
aws.s3.accessKey=<YOUR_DEV_AWS_ACCESS_KEY>
aws.s3.secretKey=<YOUR_DEV_AWS_SECRET_KEY>
aws.s3.region=ap-south-1
aws.s3.folder-name=aws-woc-dev