spring.application.name=config-server
server.port=9510
spring.profiles.active=dev
spring.cloud.config.server.git.uri=https://<YOUR_GIT_USERNAME>@<YOUR_GIT_PROVIDER_URL>/<YOUR_ORGANIZATION>/<YOUR_CONFIG_REPO_NAME>.git
spring.cloud.config.server.git.username=<YOUR_GIT_USERNAME>
spring.cloud.config.server.git.password=<YOUR_GIT_ACCESS_TOKEN_OR_APP_PASSWORD>
spring.security.user.name=<YOUR_CONFIG_SERVER_USERNAME>
spring.security.user.password=<YOUR_CONFIG_SERVER_PASSWORD>
#Debugging
logging.level.org.springframework.security=DEBUG